### ISSUE TITLE
Checking for duplicate url_key for products is not correct for Schedule Updates

### ISSUE THREAD

**Issue by abukatar** [ydenyshchenk/Sparta_UrlRewriteRebuilder#2]
It seems like "Checking for duplicate url_key for products" step is not correct when Schedule Updates is in use.
The query generated for the step is as follow:
SELECT `cpev`.`value` AS `url_key`, COUNT(row_id) AS `count` FROM `catalog_product_entity_varchar` AS `cpev` WHERE (cpev.attribute_id = 124) GROUP BY `value` HAVING (count > 1)

While for categories, it is like the query beneath:
SELECT `cuk`.`store_id`, `cuk`.`value` AS `url_key`, COUNT(`cuk`.`row_id`) AS `count`, REPLACE(`cce`.`path`, `cce`.`entity_id`, "") AS `parent_path`, GROUP_CONCAT(`cuk`.row_id) AS `ids`, `cup`.`value` AS `url_path` FROM `catalog_category_entity_varchar` AS `cuk`
 INNER JOIN `catalog_category_entity` AS `cce` ON cce.row_id = cuk.row_id AND (cce.created_in <= '1504223940' AND cce.updated_in > '1504223940')
 INNER JOIN `catalog_category_entity_varchar` AS `cup` ON cce.row_id = cup.row_id AND cup.store_id = cuk.store_id  AND cup.attribute_id = 123 WHERE (cuk.attribute_id = 122) GROUP BY `url_key`,
	`parent_path`,
	`store_id` HAVING (count > 1)

**Comment by ydenyshchenk** [comment]
Fixed in **master** and **2.1.9** branches.
Thank you!
