### ISSUE TITLE
Parent constructor exclusion causing PHP null fatal error

### ISSUE THREAD

**Issue by ryandiamond23** [ydenyshchenk/Sparta_UrlRewriteRebuilder#4]
On the latest release, the parent::__constructor call was removed from the CategoryProcessor.php constructor, which causes a 500 error on admin panel when trying to save a category.

Is there a specific reason this was removed here (https://github.com/ydenyshchenk/Sparta_UrlRewriteRebuilder/commit/f0fd1d77f1f12be2fd194c39b294e2d6b598baf0#diff-b92244c36c3d12e449c0f6a650a6fdbaL37)? Our client is on 2.1.17 and this broke functionality on 2.1.x -- unsure if this has same impact on 2.2.x clients.

[Wed May 01 16:15:02.684775 2019] [proxy_fcgi:error] [pid 1319] [client 22.22.22.1:65137] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function generate() on null in /vagrant/magento/vendor/magento/module-catalog-url-rewrite/Observer/CategoryProcessUrlRewriteSavingObserver.php:97\nStack trace:\n#0 /vagrant/magento/app/code/Sparta/UrlRewriteRebuilder/Model/CategoryProcessor.php(90): Magento\\CatalogUrlRewrite\\Observer\\CategoryProcessUrlRewriteSavingObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#1 /vagrant/magento/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Sparta\\UrlRewriteRebuilder\\Model\\CategoryProcessor->execute(Object(Magento\\Framework\\Event\\Observer))\n#2 /vagrant/magento/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Sparta\\UrlRewriteRebuilder\\Model\\CategoryProcessor), Object(Magento\\Framework\\Event\\Observer))\n#3 /vagrant/magento/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, O...\n', referer: https://industrywest.test/admin/catalog/category/add/key/a039a9da73a0c58e2fb6cc51f7eb72a2abb1ec75c976efd99e033b2067f0b3b2/store/0/parent/2

**Comment by ydenyshchenk** [comment]
Fixed in https://github.com/ydenyshchenk/Sparta_UrlRewriteRebuilder/tree/2.2.6
